import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/assets/globals.css';
import { Toaster } from 'sonner';
import { ContextProvider } from '@/context/wrapper';
import Navbar from '@/components/layout/Navbar';
import { Suspense } from 'react';

// Add loading component
function LoadingState() {
    return (
        <div className="flex h-screen w-screen items-center justify-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900" />
        </div>
    );
}

const geistSans = localFont({
    src: '../assets/fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});

const geistMono = localFont({
    src: '../assets/fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Suspense fallback={<LoadingState />}>
                    <ContextProvider>
                        <Toaster richColors position="bottom-right" />
                        <Navbar />
                        {children}
                    </ContextProvider>
                </Suspense>
            </body>
        </html>
    );
}
